import tenisImg from '../../assets/image/Produto2.png';
export const cardsInfoProductPage = [
{
    id: 1,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 2,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 3,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 4,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
];