import imgTenis from "../../../assets/image/CardTenisForIN.png"
export const TenisArray = [
    {
        Id: 1,
        ProductSerieNumber: 2234981932,
        SeriesNumber: true,
        ProductName: 'Tênis Nike Revolution 6 Next Nature Masculino',
        url2: imgTenis,
        Finalizado: false,
        Cancelado: false,
        Transito: true, 
    },
    {
        Id: 2,
        ProductSerieNumber: 4495810492,
        SeriesNumber: false,
        ProductName: 'Tênis Nike Revolution 6 Next Nature Masculino',
        url2: imgTenis,
        Finalizado: true,
        Cancelado: false,
        Transito: false, 
    },
    {
        Id: 3,
        ProductSerieNumber: 4495810492,
        SeriesNumber: false,
        ProductName: 'Tênis Nike Revolution 6 Next Nature Masculino',
        url2: imgTenis,
        Finalizado: false,
        Cancelado: true,
        Transito: false, 
    },
    {
        Id: 4,
        ProductSerieNumber: 4495810492,
        SeriesNumber: false,
        ProductName: 'Tênis Nike Revolution 6 Next Nature Masculino',
        url2: imgTenis,
        Finalizado: true,
        Cancelado: false,
        Transito: false, 
    },
    {
        Id: 5,
        ProductSerieNumber: 4495810492,
        SeriesNumber: false,
        ProductName: 'Tênis Nike Revolution 6 Next Nature Masculino',
        url2: imgTenis,
        Finalizado: true,
        Cancelado: false,
        Transito: false, 
    },
]